### ISSUE TITLE
Create ISSUE_TEMPLATE/config.yml for issues rules

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#2191]
As #2110 raised, it will be great to have rules for issues.
People can miss it when it's only pinned, it would have be great to have a custom text when you create an issue.

Github do not seem to offer this possibility, to custom like that the issue creation page, but they introduced [template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser). Probably not his direct purpose, but it can reach more people than a pinned issue.

Can be something like that:
```
# config.yml
blank_issues_enabled: true
contact_links:
  - name: Issue Submission Rules
    url: https://link-to-rules.example
    about: Please consider reading them before posting.
```

Will look like that :
![Capture d’écran de 2021-05-27 17-22-19](https://user-images.githubusercontent.com/34010605/119853337-66340800-bf10-11eb-872c-a04a72c3ce8d.png)
