### ISSUE TITLE
[feat] Add Dogecoin Core to Winget

### ISSUE THREAD

**Issue by PasserDreamer** [dogecoin/dogecoin#2228]
# Feature Request

**Describe the Feature Request**

Add Dogecoin Core to [Winget.](https://github.com/microsoft/winget-pkgs)
You can edit it from below.
```
PackageIdentifier: Dogecoin.DogecoinCore
PackageVersion: 1.14.3
PackageLocale: en-US
Publisher: Dogecoin
PackageName: Dogecoin Core
License: MIT
Moniker: dogecoin
Tags:
- cryptocurrency
- crypto
- wallet
ShortDescription: Dogecoin is an open source peer-to-peer digital currency, favored by Shiba Inus worldwide. Dogecoin Core is a "full" wallet.
Installers: 
 - Architecture: x64
   InstallerUrl: https://github.com/dogecoin/dogecoin/releases/download/v1.14.3/dogecoin-1.14.3-win64-setup-unsigned.exe
   InstallerSha256: 37aafa689c193feb6d66e4ed30f9aaf899f4065a5b002f6962ce02a200d9116b
   InstallerType: nullsoft
   InstallerSwitches:
     Silent: /S
 - Architecture: x86
   InstallerUrl: https://github.com/dogecoin/dogecoin/releases/download/v1.14.3/dogecoin-1.14.3-win32-setup-unsigned.exe
   InstallerSha256: 74190511fd882631ca4b467715ec26771eb4ba3cb0e8896f50d6dc840ee0cfd7
   InstallerType: nullsoft
   InstallerSwitches:
     Silent: /S
ManifestType: singleton
ManifestVersion: 1.0.0
```
