### ISSUE TITLE
getrawtransaction node api  

### ISSUE THREAD

**Issue by Rasika9596** [dogecoin/dogecoin#2419]
Hello,

I tried the same APIs of bitcoin on the Doge node and its working file except the API to get transaction details from transaction hash.

API I'm using:

```
curl --location --request POST 'http://----:22555' \
--header 'Authorization: Basic -------' \
--header 'Content-Type: text/plain' \
--data-raw '{"jsonrpc":"1.0","id":"2","method":"getrawtransaction","params":["c20b2912d4b864bc4cdde57e3fd402c1f296b391a2a816ec5a50ecfc278ccd6a", true, "de92536d5ef5aef5aa7feef6b736b6ef111b02cf996947bd2c6df7dded5d4d0f"]}'
```

Response I'm getting is:

`{"result":null,"error":{"code":-1,"message":"getrawtransaction \"txid\" ( verbose )\n\nNOTE: By default this function only works for mempool transactions. If the -txindex option is\nenabled, it also works for blockchain transactions.\nDEPRECATED: for now, it also works for transactions with unspent outputs.\n\nReturn the raw transaction data.\n\nIf verbose is 'true', returns an Object with information about 'txid'.\nIf verbose is 'false' or omitted, returns a string that is serialized, hex-encoded data for 'txid'.\n\nArguments:\n1. \"txid\"      (string, required) The transaction id\n2. verbose       (bool, optional, default=false) If false, return a string, otherwise return a json object\n\nResult (if verbose is not set or set to false):\n\"data\"      (string) The serialized, hex-encoded data for 'txid'\n\nResult (if verbose is set to true):\n{\n  \"hex\" : \"data\",       (string) The serialized, hex-encoded data for 'txid'\n  \"txid\" : \"id\",        (string) The transaction id (same as provided)\n  \"hash\" : \"id\",        (string) The transaction hash (differs from txid for witness transactions)\n  \"size\" : n,             (numeric) The serialized transaction size\n  \"vsize\" : n,            (numeric) The virtual transaction size (differs from size for witness transactions)\n  \"version\" : n,          (numeric) The version\n  \"locktime\" : ttt,       (numeric) The lock time\n  \"vin\" : [               (array of json objects)\n     {\n       \"txid\": \"id\",    (string) The transaction id\n       \"vout\": n,         (numeric) \n       \"scriptSig\": {     (json object) The script\n         \"asm\": \"asm\",  (string) asm\n         \"hex\": \"hex\"   (string) hex\n       },\n       \"sequence\": n      (numeric) The script sequence number\n       \"txinwitness\": [\"hex\", ...] (array of string) hex-encoded witness data (if any)\n     }\n     ,...\n  ],\n  \"vout\" : [              (array of json objects)\n     {\n       \"value\" : x.xxx,            (numeric) The value in DOGE\n       \"n\" : n,                    (numeric) index\n       \"scriptPubKey\" : {          (json object)\n         \"asm\" : \"asm\",          (string) the asm\n         \"hex\" : \"hex\",          (string) the hex\n         \"reqSigs\" : n,            (numeric) The required sigs\n         \"type\" : \"pubkeyhash\",  (string) The type, eg 'pubkeyhash'\n         \"addresses\" : [           (json array of string)\n           \"address\"        (string) dogecoin address\n           ,...\n         ]\n       }\n     }\n     ,...\n  ],\n  \"blockhash\" : \"hash\",   (string) the block hash\n  \"confirmations\" : n,      (numeric) The confirmations\n  \"time\" : ttt,             (numeric) The transaction time in seconds since epoch (Jan 1 1970 GMT)\n  \"blocktime\" : ttt         (numeric) The block time in seconds since epoch (Jan 1 1970 GMT)\n}\n\nExamples:\n> dogecoin-cli getrawtransaction \"mytxid\"\n> dogecoin-cli getrawtransaction \"mytxid\" true\n> curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"getrawtransaction\", \"params\": [\"mytxid\", true] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/\n"},"id":"2"}`

docker-compose file:
```

version: '2'
services:
    node-dogecoin:
        image: dogecoin
        container_name: dogecoin_container
        restart: always
        ports:
            - "22555:22555"
            - "22556:22556"
        environment:
            PRINTTOCONSOLE: 1
            RPCUSER: "test"
            RPCPASSWORD: "test123"
        volumes:
            - $(pwd)/data:/dogecoin/.dogecoin
        command:
            - "-onlynet=ipv4"
            - "-txindex"
            - "-rpcthreads=128"
            - "-dbcache=1024"
            - "-rpcallowip=0.0.0.0/0"
            - "-rpcbind=127.0.0.1"
            - "-rpcbind=dogecoin_container"
            - "-blocksonly=1"
        mem_limit: 5g
```

Can anyone please help me why I'm getting the error?
